steps:
  - command: .buildkite/scripts/steps/storybooks/build_and_upload.sh
    label: 'Build Storybooks'
    agents:
      machineType: n2-standard-8
      preemptible: true
      diskSizeGb: 75
    key: storybooks
    timeout_in_minutes: 80
