steps:
  - command: .buildkite/scripts/steps/es_snapshots/build.sh
    label: Build ES Snapshot
    timeout_in_minutes: 30
    agents:
      image: kibana-ubuntu-2004-1729722506
      imageProject: elastic-images-qa
      provider: gcp
      localSsds: 1
      localSsdInterface: nvme
      machineType: c2-standard-8
