steps:
  - command: .buildkite/scripts/steps/artifacts/trigger.sh
    label: Trigger artifacts build
    agents:
      image: kibana-ubuntu-2004-1729722506
      imageProject: elastic-images-qa
      provider: gcp
      machineType: n2-standard-2
    timeout_in_minutes: 10
